### PR TITLE
two tabs display

### PR DESCRIPTION
**Pull request by buthanoid**
associated to issue https://github.com/JMMC-OpenDev/oimaging/issues/21

### CODE REVIEW

**Comment by bourgesl** [comment]
Please rebase your PR with master as there are conflicts, sorry !

**Comment by buthanoid** [comment]
No problem I do it usually I was waiting a little to be sure to do it once and not twice.
Can I use git-merge or do you prefer git-rebase ?

**Comment by bourgesl** [comment]
Please merge, hope conflicts will be easy, or I can manage it

**Comment by buthanoid** [comment]
### Technical review

Instead of one, `MainPanel` has now two instances of the class `ViewerPanel`: `viewerPanelInput` and `viewerPanelResults`.
`viewerPanelInput` is used to display only Fits from the input form, i.e from `IRModel.oifitsFile`.
`viewerPanelResults` is used to display only Fits from results, i.e from `IRModel.serviceResults`.

A tabbed pane has been added as a direct child of `mainPanel`. The first tab contains input form and the `viewerPanelInput`. The second tab contains the `viewerPanelResults` and the `ResultSetTablePanel`.

A lot of modified lines in the PR consists of renaming (for example `viewerPanel` to `viewerPanelInput`). Most of the time, it consists of choosing the good `viewerPanel` (for example, deciding to display only one result or a grid of result always concerns the `viewerPanelResults`, and never concerns the `viewerPanelInput`). Sometimes, both `viewerPanel` are candidates, for example in the action `ExportFitsImageAction`, which is valid for both panels. So a function `MainPanel.getViewerPanelActive() `has been added and gives information about the currently displayed `viewerpanel`.

Behaviour about events in `MainPanel.syncUI` has been updated.
in case of `IRMODEL_CHANGED`, `viewerPanelInput.displayModel()` is called, and the tab is switched to Input.
In case of `IRMODEL_RESULT_LIST_CHANGED`, there is a bit more.
Since we now have a Results tab, we now face the situation of the `viewerPanelResults` having to display something even when they are no results at all. So I made small updates to make sure the `viewerpanel` data is clean. see commit https://github.com/JMMC-OpenDev/oimaging/pull/64/commits/9fa731a0974f9c3e9ab3110c0fa4149e95c20b7d .
Note that in case of a Run's result, we need to update *both* `viewerPanels`. Indeed the result will be added to the list, but it will also modify input form (change init image for example).
The tab is switched to Result.

Now that there is two `viewerPanels`, the code enabling or disabling the actions to export and send Fits file and images files was obsolete. I moved the code from `ViewerPanel` to `MainPanel`, because it needs the information about both panels to take the decision. Indeed you can export an image only if the currently active viewer panel is displaying an image. I also added a call to the function enabling the actions when the tab is switched. 
I also had to make a bit of bug fixes sometimes not pretty, like checking the state of start of the application, because the events of changing tabs was sent too soon in the startup. see commit https://github.com/JMMC-OpenDev/oimaging/pull/64/commits/c2743e591afe9757969ac8e5f7525bfec373c349 .

**Comment by buthanoid** [comment]
### Bug of OIData by Guillaume

#### Description
At the loading of a first Oifitsfile in input form, the result viewer panel shows oi data of the loaded file, whereas it should be showing no data at all (the result list is empty).

#### Scenario
- Start a clean OImaging
- Load an OIfitsfile in input form, one with data
- Observe that in the input viewer, the data is correctly displayed
- Observe that in the output viewer, the data is here too ! Problem it should have no data

#### Technical observations
I thought that two instances of ViewerPanel are independant. This bug report makes me think that at the contrary, they do share some data. 
I can investigate, but before Laurent do you have a clue ? Do you think they are sharing data or is it something else ?

**Comment by buthanoid** [comment]
### Bug of Modify Image by Ferréol

#### Description

When you modify an image, then go back to the results and click on modify the image again, behind the dialog and before confirm the dialog, in the background the viewerPanel has changed the displayed image ! Whereas nothing should happen during the dialog.

#### Scenario

- Open a clean OImaging
- Generate a result
- Go to the result in result tab
- Click on Modify Image and add 100 of FOV (so the difference is clear)
- Normally the GUI drives you to the Input tab automatically with the modified image in INIT_IMG
- Touch nothing ! Click directly on the result tab.
- Normally you still see the original image (unmodified)
- Click on "Modify Image" and do not confirm, touch nothing
- Observe that in the background the result viewer panel has updated : it now display the modified image !
- Problem : it should still display the unmodified image.

**Comment by bourgesl** [comment]
> ### Bug of OIData by Guillaume
> #### Description
> 
> At the loading of a first Oifitsfile in input form, the result viewer panel shows oi data of the loaded file, whereas it should be showing no data at all (the result list is empty).
> #### Scenario
> 
>     * Start a clean OImaging
> 
>     * Load an OIfitsfile in input form, one with data
> 
>     * Observe that in the input viewer, the data is correctly displayed
> 
>     * Observe that in the output viewer, the data is here too ! Problem it should have no data
> 
> 
> #### Technical observations
> 
> I thought that two instances of ViewerPanel are independant. This bug report makes me think that at the contrary, they do share some data. I can investigate, but before Laurent do you have a clue ? Do you think they are sharing data or is it something else ?

Dans ViewerPanel, la fonction displayOiFitsAndParams() dit à son oifitsViewPanel d'utiliser la structure OIFITS référencée (pointeur) par le parametre oifitsFile :
```
  // Display Oifits and Params
    private void displayOiFitsAndParams(OIFitsFile oifitsFile, String targetName) {
        if (oifitsFile != null) {
            oifitsViewPanel.plot(oifitsFile, targetName);
```
Donc ton leak est surement lié à un problème où tes 2 viewer panels pointent vers la même structure OIFITS ?
Il me semble que lors du chargement d'un OIFITSFile, IRModel.oifitsFile (singleton) doit utiliser une nouvelle structure vide ou chargée depuis OIFitsLoader => nouvelle référence.
As-tu modifié cela ?

**Comment by buthanoid** [comment]
I thought I checked well that the `ViewerPanel` fields contained no static field. But I failed to read the comments. The `ViewerPanel` has a field of class `OIFitsViewPanel`, and the latter has a field `OIFitsCollectionManager`. But this `OIFitsCollectionManager` field is in fact a singleton (btw it should be declared as a static field, but I should read comments).

So each `ViewerPanel` has its own `OIFitsViewPanel`, but there is only one `OIFitsCollectionManager`.
I looked a bit, it seems an interesting class that handle a collection of `OIFitsFile`, it could have some methods to help us when we will work on the Session thing.

From what I could understand, `OIFitsViewPanel` makes a very restricted use of `OIFitsCollectionManager`, see the plot function https://github.com/JMMC-OpenDev/oimaging/blob/5600bd15d5502eb8c0419de9f180cd2d46f30d0a/src/main/java/fr/jmmc/oimaging/gui/OIFitsViewPanel.java#L176 
Each time you ask to plot something, the function resets the Oifits collection and adds only its file. 

I think a bit if this `OIFitsCollectionManager` could allow us to have several plots and to ask the good plot from the `ViewerPanel`, but it would take me some time to manage to do it.
So I think maybe Laurent's suggestion is easier: ask for display every time in `MainPanel.syncUI`. Currently the switching of a tab does not trigger `syncUI`, that is why `displayResult(null)` is not called, so the `OIFitsCollectionManager` is not reset, so we see the input OIdata in the results tab. So I would change this.

**Comment by buthanoid** [comment]
The last commit https://github.com/JMMC-OpenDev/oimaging/pull/64/commits/c29028ac284adfd844e211ca965efed540bc1aa9 is to fix the issue https://github.com/JMMC-OpenDev/oimaging/issues/81

I should have down a separate PR but the mistake was made, sorry

**Comment by bourgesl** [comment]
I found a bug: the result view panel is not initialized at startup nor reset when clicking on 'New OImage file', the previous results + table are still displayed.
The result view panel should be refreshed when MODEL_CHANGED event is fired like display(null) to ensure the panel is in proper state ...

**Comment by bourgesl** [comment]
Looks good to me

**Comment by bourgesl** [comment]
Please fix the ViewerPanel jTabbedPaneVizualizations tabs: use constants + OImagingDocJUnitTest

Fix the label dimensions in MainPanel to use SwingUtils.adjustUISize():
```
        jLabelTabInput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTabInput.setText("Input");
        jLabelTabInput.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabelTabResults.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTabResults.setText("Results");
        jLabelTabResults.setPreferredSize(new java.awt.Dimension(200, 40));
```

**Comment by bourgesl** [comment]
Looks good, the basic junit test passes

**Comment by buthanoid** [comment]
I think the new use of OCM has made the GUI a bit slow. You can see it while using the ruler to run through the results. I am going to investigate

**Comment by bourgesl** [comment]
I do not see currently any performance issue.

**Comment by buthanoid** [comment]
Summary in  https://github.com/JMMC-OpenDev/oimaging/issues/21#issuecomment-1020993103

**Comment by gmella** [comment]
:+1:

**Pull request merged**
