### PR TITLE
flux err can be changed by user again

### PR DESCRIPTION
**Pull request by buthanoid**
- re-enabled the input field FLUX_ERR
- removed the manual disabling of the visibility of the field and label FLUX_ERR

### CODE REVIEW

**Comment by bourgesl** [comment]
It is more complicated as FLUX_ERR defaults depend on the IR software used; it was only valid as the field was no more editable by the user.
Test case: change selected software, then the default FLUX_ERR field should be reset (to default) but how to handle user inputs (overwrite or not) ?

**Comment by buthanoid** [comment]
I think it was handled by setting the default under the condition "applyDefaults" (instead of setting in no matter the condition, as it is currently done).
 I'm going to investigate

**Comment by bourgesl** [comment]
To be tested carefully: defaults vs user-edited values ...

**Comment by buthanoid** [comment]
Frankly I'm lost and I could not generate a case where the value of `applyDefault` had any consequence

**Comment by bourgesl** [comment]
Just move setFluxErr() calls in SoftwareParams.update() to be done within the if (applyDefaults) clause

**Pull request merged**
